### ISSUE TITLE
No need to store the user password on the device

### ISSUE THREAD

**Issue by dkastl** [Georepublic/lobsta_client#26]
Even if a personal mobile phone can be seen as safe to store the user credentials including password, for using the Redmine API username and password are only needed to authenticate to retrieve an authentication token.

Reasons to just store this token on the device:
- there is no real benefit/use case of storing the password
- not storing it means no responsibility of storing it properly
- a leaked password can cause troubles due to the way users handle passwords (i.e. reusing passwords) while a leaked authentication token can be easily revoked.
- it's not seen as good practice to store passwords unencrypted

Or is there any arguments for storing it?

**Comment by mbasa-georepublic** [comment]
This is very strange logic since the stored **KEY** in the device can wreck more havoc than the password since the **KEY** can create/update/delete issues and list all the users and their roles, etc. 

With CTI, I had to store the password since the KEY is not returned when creating a new user. And the KEY originally expired every day, so it was necessary to check if the KEY has expired, and if expired login again with the password. This of course had to be seamless to the user.   

But OK, I will blank out the password and not store it in the device.
